# Querying CTAO SDC ObsCore metadata through TAP

This notebook demonstrates how to query the CTAO Science Data Challenge ObsCore table directly from Python using the Virtual Observatory TAP protocol.

TAP service:

`http://voparis-tap-he.obspm.fr/tap`

ObsCore table:

`ctao_sdc.obscore`

In [1]:
from textwrap import dedent

import pandas as pd
import pyvo as vo

TAP_URL = "http://voparis-tap-he.obspm.fr/tap"
OBSCORE_TABLE = "ctao_sdc.obscore"

service = vo.dal.TAPService(TAP_URL)

In [2]:
query = dedent(f"""
    SELECT TOP 10
        obs_id,
        dataproduct_type,
        calib_level,
        target_name,
        s_ra,
        s_dec,
        t_min,
        t_max,
        em_min,
        em_max,
        access_url
    FROM {OBSCORE_TABLE}
""")

results = service.search(query)
table = results.to_table()
df = table.to_pandas()

df.head()

,obs_id,dataproduct_type,calib_level,target_name,s_ra,s_dec,t_min,t_max,em_min,em_max,access_url
0,5000000396,event-list,2,KSP: Transients-GRB - Event #355,107.177099,-3.099358,61797.110564,61797.168377,6.213929e-21,9.848414e-17,http://voparis-tap-he.obspm.fr/ctao_sdc/q/data...
1,5000000379,event-list,2,EGal Survey,216.770682,18.639032,61796.258785,61796.272673,6.213929e-21,9.848414e-17,http://voparis-tap-he.obspm.fr/ctao_sdc/q/data...
2,5000000400,event-list,2,AGN-Flares-External - 3C 279,194.750115,-5.788880,61797.179991,61797.185778,6.213929e-21,9.848414e-17,http://voparis-tap-he.obspm.fr/ctao_sdc/q/data...
3,5000000050,event-list,2,AGN-LTM - 1ES 1426+428,218.087902,42.668573,61773.266262,61773.271470,6.213929e-21,9.848414e-17,http://voparis-tap-he.obspm.fr/ctao_sdc/q/data...
4,5000000545,event-list,2,EGal Survey,199.126962,20.474524,61801.046042,61801.091701,6.213929e-21,9.848414e-17,http://voparis-tap-he.obspm.fr/ctao_sdc/q/data...

The result is an Astropy table converted to a Pandas DataFrame. Each row corresponds to one dataset or observation product described by ObsCore metadata.

In [3]:
metadata_query = dedent(f"""
    SELECT TOP 57
        column_name,
        datatype,
        description,
        unit,
        ucd
    FROM TAP_SCHEMA.columns
    WHERE table_name = '{OBSCORE_TABLE}'
    ORDER BY column_name
""")

columns = service.search(metadata_query).to_table().to_pandas()
columns.head(57)

,column_name,datatype,description,unit,ucd
0,access_estsize,long,Estimated size of data product,kbyte,phys.size;meta.file
1,access_format,char,MIME type of the resource at access_url,,meta.code.mime
2,access_url,char,The URL at which to obtain the data set.,,meta.ref.url
3,access_url_this,char,URL for direct download of the event-list,,meta.ref.url
4,analysis_mode,char,Data reduction/analysis mode,,meta.code;obs.param
5,calib_level,short,Amount of data processing that has been applie...,,meta.code;obs.calib
6,coverage,char,"introduces an ascii (ST)MOC, v2 (2D footprint ...",,pos.outline;obs.field
7,datalink,char,URL of a datalink document for this dataset,,meta.ref.url
8,dataproduct_subtype,char,Data product specific type,,meta.code.class
9,dataproduct_type,char,High level scientific classification of the da...,,meta.code.class
10,em_max,float,Maximal wavelength represented within the data...,m,em.wl;stat.max
11,em_min,float,Minimal wavelength represented within the data...,m,em.wl;stat.min
12,em_ref_energy,double,Energy at which the ObsCore spectral character...,eV,meta.ref;em.energy;em
13,em_ref_oaa,double,"Off-axis angle (i.e., the angular separation o...",deg,pos.posAng;instr.offset;em
14,em_res_power,float,Spectral resolving power lambda/delta lambda,,spect.resolution
15,em_ucd,char,Nature of the product's spectral axis (typical...,,meta.ucd
16,em_xel,int,Number of elements (typically pixels) along th...,,meta.number
17,energy_max,double,Energy associated to the ObsCore attribute em_...,eV,em.energy;stat.max
18,energy_min,double,Energy associated to the ObsCore attribute em_...,eV,em.energy;stat.min
19,event_type,char,"Event subset indicator (e.g., data quality fla...",,meta.code.qual;obs.event
20,ev_xel,int,Number of events in an event list,,meta.number;obs.event
21,facility_name,char,Name of the facility at which data was taken,,meta.id;instr.tel
22,instrument_name,char,Name of the instrument that produced the data,,meta.id;instr
23,lfn,char,Logical File Name in Sciuence Archive,,meta.ref.url
24,messenger,char,"Messenger particle type (e.g., photon, cosmicr...",,
25,obs_collection,char,"Name of a data collection (e.g., project name)...",,meta.id
26,obs_creator_did,char,Dataset identifier assigned by the creator.,,meta.id
27,obs_id,char,Unique identifier for an observation,,meta.id
28,obs_mode,char,Observation mode of an observation,,meta.code;obs.param
29,obs_publisher_did,char,Dataset identifier assigned by the publisher.,,meta.ref.ivoid
30,obs_title,char,Free-from title of the data set,,meta.title;obs
31,o_ucd,char,UCD for the product's observable,,meta.ucd
32,pointing_mode,char,Pointing mode of an observation,,meta.code;obs.param
33,pol_states,char,List of polarization states in the data set,,meta.code;phys.polarization
34,pol_xel,int,Number of elements (typically pixels) along th...,,meta.number
35,preview,char,"URL of a preview (low-resolution, quick-to-ret...",,meta.ref.url;meta.preview
36,scan_mode,char,Scan mode of an observation,,meta.code;obs.param
37,scs_id,char,observation id for simple cone search,,meta.id;meta.main
38,s_dec,double,"Dec of (center of) observation, ICRS",deg,pos.eq.dec
39,s_fov,float,Approximate spatial extent for the region cove...,deg,phys.angSize;instr.fov
40,source_table,char,Name of a TAP-queriable table this data origin...,,meta.id;meta.table
41,s_pixel_scale,float,Sampling period in world coordinate units alon...,arcsec,phys.angSize;instr.pixel
42,s_ra,double,"RA of (center of) observation, ICRS",deg,pos.eq.ra
43,s_ref_energy,double,Energy at which the ObsCore spatial characteri...,eV,meta.ref;em.energy;pos
44,s_ref_oaa,double,"Off-axis angle (i.e., the angular separation o...",deg,pos.posAng;instr.offset;pos
45,s_region,char,"Region covered by the observation, as a polygon",,pos.outline;obs.field
46,s_resolution,float,Best spatial resolution within the data set,arcsec,pos.angResolution
47,s_xel1,int,Number of elements (typically pixels) along th...,,meta.number
48,s_xel2,int,Number of elements (typically pixels) along th...,,meta.number
49,target_class,char,"Class of the target object (star, QSO, ...)",,src.class
50,target_name,char,Object a targeted observation targeted,,meta.id;src
51,t_exptime,float,Total exposure time,s,time.duration;obs.exposure
52,t_intervals,char,List of observation intervals or stable/good t...,,
53,t_max,double,Upper bound of times represented in the data set,d,time.end;obs.exposure
54,t_min,double,Lower bound of times represented in the data set,d,time.start;obs.exposure
55,tracking_mode,char,"Tracking mode of an observation (e.g., siderea...",,meta.code;obs.param
56,t_resolution,float,Minimal significant time interval along the ti...,s,time.resolution

In [4]:
# M82
ra = 148.968458
dec = 69.679703
radius_deg = 5.0

region_query = dedent(f"""
    SELECT TOP 50
        obs_id,
        target_name,
        s_ra,
        s_dec,
        t_min,
        t_max,
        em_min,
        em_max
    FROM {OBSCORE_TABLE}
    WHERE 1 = CONTAINS(
        POINT('ICRS', s_ra, s_dec),
        CIRCLE('ICRS', {ra}, {dec}, {radius_deg})
    )
""")

region_df = service.search(region_query).to_table().to_pandas()
region_df.head()

,obs_id,target_name,s_ra,s_dec,t_min,t_max,em_min,em_max
0,5000000007,SFS - M82,150.983459,69.668154,61771.164086,61771.219641,6.213929e-21,9.848414e-17
1,5000000174,SFS - M82,148.968455,68.979698,61789.010521,61789.013935,6.213929e-21,9.848414e-17
2,5000000070,SFS - M82,148.968455,68.979698,61775.093738,61775.131875,6.213929e-21,9.848414e-17
3,5000000162,SFS - M82,148.968455,70.379698,61788.006551,61788.009965,6.213929e-21,9.848414e-17
4,5000000163,SFS - M82,148.968455,68.979698,61788.010023,61788.013437,6.213929e-21,9.848414e-17